{{- if (and (not .Values.customTLSCertificate) (not .Values.certManager.enabled)) }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "nri-metadata-injection.fullname.admission-patch" . }}
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
  labels:
    {{- include "newrelic.common.labels" . | nindent 4 }}
    app: {{ include "nri-metadata-injection.name.admission-patch" . }}
spec:
  template:
    metadata:
      name: {{ include "nri-metadata-injection.fullname.admission-patch" . }}
      labels:
        {{- include "newrelic.common.labels" . | nindent 8 }}
        app: {{ include "nri-metadata-injection.name.admission-patch" . }}
    spec:
      {{- if .Values.jobImage.pullSecrets }}
      imagePullSecrets:
{{ toYaml .Values.jobImage.pullSecrets | indent 8 }}
      {{- end }}
      containers:
        - name: patch
          image: {{ include "newrelic.common.images.image" ( dict "imageRoot" .Values.jobImage "context" .) }}
          imagePullPolicy: {{ .Values.jobImage.pullPolicy }}
          args:
            - patch
            - --webhook-name={{ include "newrelic.common.naming.fullname" . }}
            - --namespace={{ .Release.Namespace }}
            - --secret-name={{ include "nri-metadata-injection.fullname.admission" . }}
            - --patch-failure-policy=Ignore
            - --patch-validating=false
          {{- if .Values.jobImage.volumeMounts }}
          volumeMounts:
          {{- include "tplvalues.render" ( dict "value" .Values.jobImage.volumeMounts "context" $ ) | nindent 10 }}
          {{- end }}
      {{- if .Values.jobImage.volumes }}
      volumes:
      {{- include "tplvalues.render" ( dict "value" .Values.jobImage.volumes "context" $ ) | nindent 8 }}
      {{- end }}
      restartPolicy: OnFailure
      serviceAccountName: {{ include "nri-metadata-injection.fullname.admission" . }}
      securityContext:
        runAsGroup: 2000
        runAsNonRoot: true
        runAsUser: 2000
      {{- if .Values.tolerations }}
      tolerations:
        {{- toYaml .Values.tolerations | nindent 8 }}
      {{- end }}
{{- end }}
