apiVersion: v2

name: nri-metadata-injection
description: A Helm chart to deploy the New Relic metadata injection webhook.

home: https://hub.docker.com/r/newrelic/k8s-metadata-injection
icon: https://newrelic.com/assets/newrelic/source/NewRelic-logo-square.svg
sources:
  - https://github.com/newrelic/k8s-metadata-injection


version: 2.3.0
appVersion: 1.7.0

keywords:
  - infrastructure
  - newrelic
  - monitoring

dependencies:
  - name: common-library
    version: 1.0.0
    repository: "https://helm-charts.newrelic.com"

maintainers:
  - name: alvarocabanas
    url: https://github.com/alvarocabanas
  - name: carlossscastro
    url: https://github.com/carlossscastro
  - name: gsanchezgavier
    url: https://github.com/gsanchezgavier
  - name: kang-makes
    url: https://github.com/kang-makes
  - name: marcsanmi
    url: https://github.com/marcsanmi
  - name: paologallinaharbur
    url: https://github.com/paologallinaharbur
  - name: roobre
    url: https://github.com/roobre
  - name: sigilioso
    url: https://github.com/sigilioso
