apiVersion: v2
description: A Helm chart to deploy the New Relic metadata injection webhook.
name: nri-metadata-injection
version: 2.3.0
appVersion: 1.7.0
home: https://hub.docker.com/r/newrelic/k8s-metadata-injection
sources:
  - https://github.com/newrelic/k8s-metadata-injection
engine: gotpl
icon: https://newrelic.com/assets/newrelic/source/NewRelic-logo-square.svg
dependencies:
  - name: common-library
    version: 1.0.0
    repository: "https://helm-charts.newrelic.com"
maintainers:
  - name: alvarocabanas
  - name: carlossscastro
  - name: gsanchezgavier
  - name: kang-makes
  - name: marcsanmi
  - name: paologallinaharbur
  - name: roobre
  - name: sigilioso
keywords:
  - infrastructure
  - newrelic
  - monitoring
