name: Security Scan

on:
  workflow_call:
    # secrets need to be passed in for reusable workflows
    secrets:
      slack_channel: 
        description: slack channel for notifications
        required: true
      slack_token: 
        description: slack token for slack channel
        required: true

env:
  ORIGINAL_REPO_NAME: ${{ github.event.repository.full_name }}

jobs:
  trivy:
    name: Trivy security scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Trivy vulnerability scanner in repo mode
        uses: aquasecurity/trivy-action@0.14.0
        if: ${{ ! github.event.schedule }} # Do not run inline checks when running periodically
        with:
          scan-type: fs
          ignore-unfixed: true
          severity: 'HIGH,CRITICAL'
          skip-dirs: 'build'
          format: 'table'

      - name: Build integration
        env:
          GOOS: linux
          GOARCH: amd64
        run: |
          make compile

      - name: Build and load x64 image
        run: |
          docker buildx build --load --platform=linux/amd64 --tag trivy-scan:${{ github.sha }} .

      - name: Run Trivy vulnerability scanner sarif output
        uses: aquasecurity/trivy-action@0.14.0
        # Upload sarif when running periodically or pushing to main
        if: ${{ github.event.schedule || (github.event_name == 'push' && github.ref_name == 'main') }}
        with:
          image-ref: 'trivy-scan:${{ github.sha }}'
          ignore-unfixed: true
          severity: 'HIGH,CRITICAL'
          skip-dirs: 'build'
          format: 'sarif'
          output: 'trivy-results.sarif'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        # Upload sarif when running periodically or pushing to main
        if: ${{ github.event.schedule || (github.event_name == 'push' && github.ref_name == 'main') }}
        with:
          sarif_file: 'trivy-results.sarif'

  notify-failure:
    if: ${{ always() && failure() && (github.event_name == 'schedule') }}
    needs: [trivy]
    runs-on: ubuntu-latest
    steps:
      - name: Notify failure via Slack
        uses: archive/github-actions-slack@cb6f1f6bc7bfe991ea956833f9515dac40da14d2 # v2.8.0
        with:
          slack-bot-user-oauth-access-token: ${{ secrets.slack_token }}
          slack-channel: ${{ secrets.slack_channel }}
          slack-text: "‚ùå `${{ env.ORIGINAL_REPO_NAME }}`: <${{ github.server_url }}/${{ env.ORIGINAL_REPO_NAME }}/actions/runs/${{ github.run_id }}|'Security Scan' failed>."
